####################################################################################
###
### cryptix-miner
### https://github.com/cryptix-network/cryptix-miner/releases
###
### Cryptix is sexy - I swear
###
####################################################################################

# The name of the miner
CUSTOM_NAME=cryptix_miner_hive_sheet_v029

# Optional version of your custom miner package
CUSTOM_VERSION=v0.2.9
CUSTOM_BUILD=0
CUSTOM_MINERBIN=cryptix-miner

# Full path to miner config file
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/cryptix_miner_hive_sheet_v029/config.ini

# Full path to log file basename. WITHOUT EXTENSION (don't include .log at the end)
CUSTOM_LOG_BASENAME=/var/log/miner/cryptix_miner_hive_sheet_v029

WEB_PORT=3338